#!/usr/bin/env ruby

# frozen_string_literal: true

require "bundler/inline"
require_relative "lib/styr"

gemfile do
  source "https://rubygems.org"

  gem "toml-rb"
  gem "tty-command"
  gem "tty-table"
end

input_command = ARGV.first.to_s.downcase
app = Styr.instance
app.process_input_command(input_command, ARGV[1..])
